#!/bin/bash
#SBATCH -N 1
#SBATCH -n 48
#SBATCH -p checkpt
#SBATCH -A loni_pgtrain3
#SBATCH -t 72:00:00
#SBATCH -o slurm-%j.out-%N
#SBATCH -e slurm-%j.err-%N
#SBATCH --mail-user mfo010@email.latech.edu
#SBATCH --mail-type ALL
#job starts here
date
echo "job started!"
echo "loading modules!"
module list
echo " "
echo "currently in $PWD"
echo "moving to /work/mjfos2r/denovo/trinity/trinity_rRNA_culled/kallisto"
cd /ddnA/work/mjfos2r/denovo/trinity/trinity_rRNA_culled/kallisto_no_rRNA
echo "currently in: $PWD"
echo " "
echo "setting kallisto output directory"
export KALLISTO_OUT=/ddnA/work/mjfos2r/denovo/trinity/trinity_rRNA_culled/kallisto_no_rRNA
echo "KALLISTO_OUT = $KALLISTO_OUT"
echo " "
echo "index already exists"
echo "SKIPPED DUE TO ALREADY HAVING AN INDEX"
echo "SKIPPED: echo "starting kallisto index""
echo "SKIPPED: kallisto index -i ../clustering/centroids.fasta.index ../clustering/centroids.fasta"
echo "SKIPPED: echo "index complete!""
echo "index already exists!"
echo " "
echo "setting kallistoindex variable to /ddnA/work/mjfos2r/denovo/trinity/first_assembly/kallisto/centroids.fasta.index"
export KALLISTOINDEX=/ddnA/work/mjfos2r/denovo/trinity/trinity_rRNA_culled/clustering/centroids.fasta.index
echo "KALLISTOINDEX = $KALLISTOINDEX"
echo " "
echo "moving to /ddnA/work/mjfos2r/denovo/bowtie2_rRNA_out"
cd /ddnA/work/mjfos2r/denovo/bowtie2_rRNA_out
echo "currently in: $PWD"
echo " "
echo "beginning kallisto quant loop!"
date
for i in whitelisted_trimmed.*.fq.gz
do
echo "starting kallisto quant on read ${i}"
kallisto quant -i $KALLISTOINDEX \
-o $KALLISTO_OUT/${i} \
-t 48 \
--single -l 150 -s 20 \
${i}
echo " "
echo "Sample Done! continuing loop onto next sample!"
echo " "
done
echo "Kallisto Quant complete!"
echo "be sure to run NOISeq, Gfold, and DESeq2 next!"
echo " "
echo "Job Complete!"
date
exit 0
